#pragma once

// Typed service interface base contract (spec 003-typed-service-interface).
//
// The actual interface (IXxxService), proxy (XxxServiceProxy) and
// registration helper (RegisterService) are GENERATED by protoc-gen-urpc
// (--urpc_out) from the .proto service description - see
// specs/003-typed-service-interface/contracts/service-interface.md.
//
// This header only carries the shared descriptor type consumed by the
// generated method tables and their contract tests.

namespace urpc {

// One entry per remote method in a generated interface's kMethods table
// (order = declaration order in the .proto service; mirrors the proto
// contract 1:1 - see specs/003-typed-service-interface/data-model.md).
struct MethodDescriptor {
  const char* name;  // method name, e.g. "Echo"
  const char* path;  // full route, e.g. "/example.EchoService/Echo"
};

}  // namespace urpc
